name: medpost
services:
  medpost-app:
    container_name: medpost
    build: .
    env_file: .env.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - images_volume:/app/static/images
      - data_volume:/app/data
      - logs_volume:/app/logs
  rss-fetcher:
    container_name: rss-fetcher
    build: 
      context: ../fetch_post
      dockerfile: rss_fetcher/Dockerfile
    env_file: ../fetch_post/.env.dev
    volumes:
      - ../fetch_post/rss_fetcher/:/app
      - images_volume:/app/static/images
      - data_volume:/app/data
      - logs_volume:/app/logs
  social-publisher:
    container_name: social-publisher
    build: 
      context: ../fetch_post
      dockerfile: social_publisher/Dockerfile
    env_file: ../fetch_post/.env.dev
    volumes:
      - ../fetch_post/social_publisher/:/app
      - images_volume:/app/static/images
      - data_volume:/app/data
      - logs_volume:/app/logs
  sqlite-cli:
      container_name: sqlite-cli
      image: alpine/sqlite:latest
      volumes:
        - data_volume:/data
      stdin_open: true
      tty: true
      entrypoint: sh -c "sqlite3 /data/rss_qdm.db"
      deploy:
        restart_policy:
          condition: none
volumes:
  images_volume:
  data_volume:
    external: true
  logs_volume:
    external: true